// spirdb.proto
syntax = "proto3";

package skim.spir;

message DbParametersRequest { }

message DbParametersReply {
  uint64 k = 1;
  uint64 s = 2;
  uint64 t = 3;
}

message DbMetadataRequest { }

message DbMetadataReply {
  map<uint32, uint64> index = 1;
  repeated string labels    = 2;
}

message SpirParametersRequest { }

message SpirParametersReply {
  uint64 n          = 1;
  double sigma      = 2;

  uint64 rle_blocks = 3;
  uint64 sqrt_N     = 4;

  uint64 log_p      = 5;
  uint64 log_q      = 6;

  uint64 seed       = 7;
}

message SpirHintRequest { }

message SpirHintReply {
  repeated uint64 hint_c = 1;
}

message QueryRequest {
  repeated uint64 qu = 1;
}

message QueryReply {
  repeated uint64 ans = 1;
}

service SpirDB {
  rpc GetDbParameters(DbParametersRequest) returns (DbParametersReply);
  rpc GetDbMetadata(DbMetadataRequest) returns (DbMetadataReply);
  rpc GetSpirParameters(SpirParametersRequest) returns (SpirParametersReply);
  rpc GetSpirHint(SpirHintRequest) returns (SpirHintReply);
  rpc Query(QueryRequest) returns (QueryReply);
}
