// siperdb.proto
syntax = "proto3";

package skim.siper;

import "google/protobuf/empty.proto";

message DbParametersReply {
  uint64 k = 1;
  uint64 s = 2;
  uint64 t = 3;
}

message SiperParametersReply {
  uint64 n              = 1;
  double sigma          = 2;

  // std::size_t
  uint64 log_p          = 3;
  uint64 log_q          = 4;

  // std::size_t
  uint64 block_size     = 5;
  uint64 batch_size     = 6;
  uint64 sqrt_N         = 7;

  uint64 seed           = 8;

  string metadata_hash  = 9;
  string hint_c_hash    = 10;
}

message QueryRequest {
  repeated uint64 qu = 1;
}

message QueryReply {
  repeated uint64 ans = 1;
}

message DataRequest {
  string hash = 1;
}

message DataChunk {
  bytes data = 1;
  uint64 offset = 2;
  uint64 total_size = 3;
}

service SiperDB {
  rpc GetDbParameters(google.protobuf.Empty) returns (DbParametersReply);
  rpc GetSiperParameters(google.protobuf.Empty) returns (SiperParametersReply);

  rpc Query(QueryRequest) returns (QueryReply);
  rpc BatchQuery(QueryRequest) returns (QueryReply);

  rpc DownloadData(DataRequest) returns (stream DataChunk);
}
